{
  "Header": {
    "Original": "CVE-2021-30178 (An issue was discovered in the Linux kernel through 5.11.11. synic_get ...)",
    "Line": 122028,
    "ID": "CVE-2021-30178",
    "Description": "(An issue was discovered in the Linux kernel through 5.11.11. synic_get ...)"
  },
  "Annotations": [
    {
      "Original": "- linux \u003cnot-affected\u003e (Vulnerable code introduced later)",
      "Line": 122029,
      "Type": "package",
      "Package": "linux",
      "Kind": "not-affected",
      "Description": "Vulnerable code introduced later"
    },
    {
      "Original": "NOTE: https://git.kernel.org/linus/919f4ebc598701670e80e31573a58f1f2d2bf918",
      "Line": 122030,
      "Type": "NOTE",
      "Description": "https://git.kernel.org/linus/919f4ebc598701670e80e31573a58f1f2d2bf918"
    }
  ]
}