{
  "Header": {
    "Original": "CVE-2020-35132 (An XSS issue has been discovered in phpLDAPadmin before 1.2.6.2 that a ...)",
    "Line": 149858,
    "ID": "CVE-2020-35132",
    "Description": "(An XSS issue has been discovered in phpLDAPadmin before 1.2.6.2 that a ...)"
  },
  "Annotations": [
    {
      "Original": "- phpldapadmin \u003cunfixed\u003e (bug #987355)",
      "Line": 149859,
      "Type": "package",
      "Package": "phpldapadmin",
      "Kind": "unfixed",
      "BugNo": 987355
    },
    {
      "Original": "NOTE: https://bugs.launchpad.net/ubuntu/+source/phpldapadmin/+bug/1906474",
      "Line": 149860,
      "Type": "NOTE",
      "Description": "https://bugs.launchpad.net/ubuntu/+source/phpldapadmin/+bug/1906474"
    },
    {
      "Original": "NOTE: https://github.com/leenooks/phpLDAPadmin/commit/c87571f6b7be15d5cd8b26381b6eb31ad03d28e2",
      "Line": 149861,
      "Type": "NOTE",
      "Description": "https://github.com/leenooks/phpLDAPadmin/commit/c87571f6b7be15d5cd8b26381b6eb31ad03d28e2"
    },
    {
      "Original": "NOTE: https://github.com/leenooks/phpLDAPadmin/issues/130",
      "Line": 149862,
      "Type": "NOTE",
      "Description": "https://github.com/leenooks/phpLDAPadmin/issues/130"
    },
    {
      "Original": "NOTE: Fix is incomplete: https://github.com/leenooks/phpLDAPadmin/issues/130#issuecomment-745152260",
      "Line": 149863,
      "Type": "NOTE",
      "Description": "Fix is incomplete: https://github.com/leenooks/phpLDAPadmin/issues/130#issuecomment-745152260"
    },
    {
      "Original": "NOTE: https://github.com/leenooks/phpLDAPadmin/issues/137",
      "Line": 149864,
      "Type": "NOTE",
      "Description": "https://github.com/leenooks/phpLDAPadmin/issues/137"
    }
  ]
}