{
  "Header": {
    "Original": "CVE-2017-6519 (avahi-daemon in Avahi through 0.6.32 and 0.7 inadvertently responds to ...)",
    "Line": 379249,
    "ID": "CVE-2017-6519",
    "Description": "(avahi-daemon in Avahi through 0.6.32 and 0.7 inadvertently responds to ...)"
  },
  "Annotations": [
    {
      "Original": "- avahi 0.7-5 (unimportant; bug #917047)",
      "Line": 379250,
      "Type": "package",
      "Package": "avahi",
      "Kind": "fixed",
      "Version": "0.7-5",
      "Severity": "unimportant",
      "BugNo": 917047
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1426712",
      "Line": 379251,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1426712"
    },
    {
      "Original": "NOTE: https://github.com/lathiat/avahi/issues/203",
      "Line": 379252,
      "Type": "NOTE",
      "Description": "https://github.com/lathiat/avahi/issues/203"
    },
    {
      "Original": "NOTE: https://github.com/lathiat/avahi/commit/e111def44a7df4624a4aa3f85fe98054bffb6b4f",
      "Line": 379253,
      "Type": "NOTE",
      "Description": "https://github.com/lathiat/avahi/commit/e111def44a7df4624a4aa3f85fe98054bffb6b4f"
    }
  ]
}