{
  "Header": {
    "Original": "CVE-2021-28302 (A stack overflow in pupnp before version 1.14.5 can cause the denial o ...)",
    "Line": 124726,
    "ID": "CVE-2021-28302",
    "Description": "(A stack overflow in pupnp before version 1.14.5 can cause the denial o ...)"
  },
  "Annotations": [
    {
      "Original": "- pupnp-1.8 \u003cunfixed\u003e (bug #986833)",
      "Line": 124727,
      "Type": "package",
      "Package": "pupnp-1.8",
      "Kind": "unfixed",
      "BugNo": 986833
    },
    {
      "Original": "[bullseye] - pupnp-1.8 \u003cno-dsa\u003e (Minor issue)",
      "Line": 124728,
      "Type": "package",
      "Release": "bullseye",
      "Package": "pupnp-1.8",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[buster] - pupnp-1.8 \u003cno-dsa\u003e (Minor issue)",
      "Line": 124729,
      "Type": "package",
      "Release": "buster",
      "Package": "pupnp-1.8",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "- libupnp \u003cremoved\u003e",
      "Line": 124730,
      "Type": "package",
      "Package": "libupnp",
      "Kind": "removed"
    },
    {
      "Original": "[stretch] - libupnp \u003cno-dsa\u003e (Minor issue)",
      "Line": 124731,
      "Type": "package",
      "Release": "stretch",
      "Package": "libupnp",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/pupnp/pupnp/issues/249",
      "Line": 124732,
      "Type": "NOTE",
      "Description": "https://github.com/pupnp/pupnp/issues/249"
    }
  ]
}