{
  "Header": {
    "Original": "CVE-2021-26932 (An issue was discovered in the Linux kernel 3.2 through 5.10.16, as us ...)",
    "Line": 132380,
    "ID": "CVE-2021-26932",
    "Description": "(An issue was discovered in the Linux kernel 3.2 through 5.10.16, as us ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2610-1 DLA-2586-1}",
      "Line": 132381,
      "Type": "xref",
      "Bugs": [
        "DLA-2610-1",
        "DLA-2586-1"
      ]
    },
    {
      "Original": "- linux 5.10.19-1",
      "Line": 132382,
      "Type": "package",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "5.10.19-1"
    },
    {
      "Original": "[buster] - linux 4.19.177-1",
      "Line": 132383,
      "Type": "package",
      "Release": "buster",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "4.19.177-1"
    },
    {
      "Original": "NOTE: https://xenbits.xen.org/xsa/advisory-361.html",
      "Line": 132384,
      "Type": "NOTE",
      "Description": "https://xenbits.xen.org/xsa/advisory-361.html"
    }
  ]
}