{
  "Header": {
    "Original": "CVE-2018-1000808 (Python Cryptographic Authority pyopenssl version Before 17.5.0 contain ...)",
    "Line": 290840,
    "ID": "CVE-2018-1000808",
    "Description": "(Python Cryptographic Authority pyopenssl version Before 17.5.0 contain ...)"
  },
  "Annotations": [
    {
      "Original": "- pyopenssl 17.5.0-1 (low)",
      "Line": 290841,
      "Type": "package",
      "Package": "pyopenssl",
      "Kind": "fixed",
      "Version": "17.5.0-1",
      "Severity": "low"
    },
    {
      "Original": "[stretch] - pyopenssl \u003cno-dsa\u003e (Minor issue)",
      "Line": 290842,
      "Type": "package",
      "Release": "stretch",
      "Package": "pyopenssl",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[jessie] - pyopenssl \u003cno-dsa\u003e (Minor issue, but also requires at least cryptography 2.1.4 which exposes the X509_up_ref method)",
      "Line": 290843,
      "Type": "package",
      "Release": "jessie",
      "Package": "pyopenssl",
      "Kind": "no-dsa",
      "Description": "Minor issue, but also requires at least cryptography 2.1.4 which exposes the X509_up_ref method"
    },
    {
      "Original": "NOTE: https://github.com/pyca/pyopenssl/pull/723",
      "Line": 290844,
      "Type": "NOTE",
      "Description": "https://github.com/pyca/pyopenssl/pull/723"
    },
    {
      "Original": "NOTE: https://github.com/pyca/pyopenssl/commit/e73818600065821d588af475b024f4eb518c3509",
      "Line": 290845,
      "Type": "NOTE",
      "Description": "https://github.com/pyca/pyopenssl/commit/e73818600065821d588af475b024f4eb518c3509"
    }
  ]
}