{
  "Header": {
    "Original": "CVE-2020-35527 (In SQLite 3.31.1, there is an out of bounds access problem through ALT ...)",
    "Line": 151146,
    "ID": "CVE-2020-35527",
    "Description": "(In SQLite 3.31.1, there is an out of bounds access problem through ALT ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3107-1}",
      "Line": 151147,
      "Type": "xref",
      "Bugs": [
        "DLA-3107-1"
      ]
    },
    {
      "Original": "- sqlite3 3.32.0-1",
      "Line": 151148,
      "Type": "package",
      "Package": "sqlite3",
      "Kind": "fixed",
      "Version": "3.32.0-1"
    },
    {
      "Original": "NOTE: https://www.sqlite.org/src/info/c431b3fd8fd0f6a6",
      "Line": 151149,
      "Type": "NOTE",
      "Description": "https://www.sqlite.org/src/info/c431b3fd8fd0f6a6"
    },
    {
      "Original": "NOTE: https://github.com/sqlite/sqlite/commit/0990c415f65d2556a5e4122cbe5727d500411aeb (version-3.32.0)",
      "Line": 151150,
      "Type": "NOTE",
      "Description": "https://github.com/sqlite/sqlite/commit/0990c415f65d2556a5e4122cbe5727d500411aeb (version-3.32.0)"
    }
  ]
}