{
  "Header": {
    "Original": "CVE-2019-3862 (An out of bounds read flaw was discovered in libssh2 before 1.8.1 in t ...)",
    "Line": 279252,
    "ID": "CVE-2019-3862",
    "Description": "(An out of bounds read flaw was discovered in libssh2 before 1.8.1 in t ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4431-1 DLA-1730-1}",
      "Line": 279253,
      "Type": "xref",
      "Bugs": [
        "DSA-4431-1",
        "DLA-1730-1"
      ]
    },
    {
      "Original": "- libssh2 1.8.0-2.1 (bug #924965)",
      "Line": 279254,
      "Type": "package",
      "Package": "libssh2",
      "Kind": "fixed",
      "Version": "1.8.0-2.1",
      "BugNo": 924965
    },
    {
      "Original": "NOTE: https://libssh2.org/CVE-2019-3862.html",
      "Line": 279255,
      "Type": "NOTE",
      "Description": "https://libssh2.org/CVE-2019-3862.html"
    },
    {
      "Original": "NOTE: Patch: https://libssh2.org/1.8.0-CVE/CVE-2019-3862.patch",
      "Line": 279256,
      "Type": "NOTE",
      "Description": "Patch: https://libssh2.org/1.8.0-CVE/CVE-2019-3862.patch"
    },
    {
      "Original": "NOTE: https://github.com/libssh2/libssh2/pull/316",
      "Line": 279257,
      "Type": "NOTE",
      "Description": "https://github.com/libssh2/libssh2/pull/316"
    }
  ]
}