{
  "Header": {
    "Original": "CVE-2020-24372 (LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in  ...)",
    "Line": 173486,
    "ID": "CVE-2020-24372",
    "Description": "(LuaJIT through 2.1.0-beta3 has an out-of-bounds read in lj_err_run in  ...)"
  },
  "Annotations": [
    {
      "Original": "- luajit \u003cunfixed\u003e (unimportant)",
      "Line": 173487,
      "Type": "package",
      "Package": "luajit",
      "Kind": "unfixed",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://github.com/LuaJIT/LuaJIT/issues/603",
      "Line": 173488,
      "Type": "NOTE",
      "Description": "https://github.com/LuaJIT/LuaJIT/issues/603"
    },
    {
      "Original": "NOTE: No security impact, only \"exploitable\" with untrusted Lua code",
      "Line": 173489,
      "Type": "NOTE",
      "Description": "No security impact, only \"exploitable\" with untrusted Lua code"
    }
  ]
}