{
  "Header": {
    "Original": "CVE-2021-33038 (An issue was discovered in management/commands/hyperkitty_import.py in ...)",
    "Line": 115472,
    "ID": "CVE-2021-33038",
    "Description": "(An issue was discovered in management/commands/hyperkitty_import.py in ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4922-1}",
      "Line": 115473,
      "Type": "xref",
      "Bugs": [
        "DSA-4922-1"
      ]
    },
    {
      "Original": "- hyperkitty 1.3.4-4 (bug #989183)",
      "Line": 115474,
      "Type": "package",
      "Package": "hyperkitty",
      "Kind": "fixed",
      "Version": "1.3.4-4",
      "BugNo": 989183
    },
    {
      "Original": "NOTE: https://gitlab.com/mailman/hyperkitty/-/commit/9025324597d60b2dff740e49b70b15589d6804fa",
      "Line": 115475,
      "Type": "NOTE",
      "Description": "https://gitlab.com/mailman/hyperkitty/-/commit/9025324597d60b2dff740e49b70b15589d6804fa"
    },
    {
      "Original": "NOTE: https://gitlab.com/mailman/hyperkitty/-/issues/380",
      "Line": 115476,
      "Type": "NOTE",
      "Description": "https://gitlab.com/mailman/hyperkitty/-/issues/380"
    },
    {
      "Original": "NOTE: https://techblog.wikimedia.org/2021/06/11/discovering-and-fixing-cve-2021-33038-in-mailman3/",
      "Line": 115477,
      "Type": "NOTE",
      "Description": "https://techblog.wikimedia.org/2021/06/11/discovering-and-fixing-cve-2021-33038-in-mailman3/"
    }
  ]
}